import { useMutation } from "convex/react";
import { Loader2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../../convex/_generated/api";

// Handles /join/:inviteCode links generated by CollaborationBar's "Copy
// invite link" button. Previously this route did not exist at all, so
// every invite link silently fell through the app's catch-all route to
// the landing page -- invites were completely non-functional. This page
// resolves the invite code via the existing (already-working) backend
// joinByInvite mutation and redirects into the real project.
export function JoinPage() {
  const { inviteCode } = useParams<{ inviteCode: string }>();
  const navigate = useNavigate();
  const joinByInvite = useMutation(api.collaboration.joinByInvite);
  const [error, setError] = useState<string | null>(null);
  const attempted = useRef(false);

  useEffect(() => {
    if (!inviteCode || attempted.current) return;
    attempted.current = true;

    (async () => {
      try {
        const projectId = await joinByInvite({ inviteCode });
        if (!projectId) {
          setError("This invite link is invalid or has expired.");
          return;
        }
        navigate(`/project/${projectId}`, { replace: true });
      } catch (e) {
        setError(e instanceof Error ? e.message : "Failed to join project.");
      }
    })();
  }, [inviteCode, joinByInvite, navigate]);

  if (error) {
    return (
      <div className="flex min-h-screen items-center justify-center px-4">
        <div className="max-w-sm text-center space-y-3">
          <p className="text-lg font-semibold text-foreground">
            Couldn't join project
          </p>
          <p className="text-sm text-muted-foreground">{error}</p>
          <button
            onClick={() => navigate("/dashboard")}
            className="text-sm text-primary underline underline-offset-4"
          >
            Back to dashboard
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen items-center justify-center">
      <div className="flex flex-col items-center gap-3">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        <p className="text-sm text-muted-foreground">Joining project…</p>
      </div>
    </div>
  );
}
